- hosts: 172.31.18.168,172.31.20.17
  become: True
  tasks:
    - name: Install apache server
      yum:
        name: httpd
        state: present
    - name: start and enable
      service:
        name: httpd
        state: started
        enabled: True
    - name: put html file on the server
      copy:
        src: index.html
        dest: /var/www/html/
    - name: Change Apache port
      lineinfile:
        path: /etc/httpd/conf/httpd.conf
        regexp: '^Listen'
        line: 'Listen 8080'
      notify:
        - restart apache
  handlers:
    - name: restart apache
        service:
          name: httpd
          state: restarted

